include:
  - ./docker-compose.infra.yml

services:
  api:
    container_name: api
    image: ghcr.io/ever-co/gauzy-api:latest
    environment:
      API_HOST: ${API_HOST:-api}
      API_PORT: ${API_PORT:-3000}
      NODE_ENV: ${NODE_ENV:-development}
      DB_HOST: db
      API_BASE_URL: ${API_BASE_URL:-http://localhost:3000}
      CLIENT_BASE_URL: ${CLIENT_BASE_URL:-http://localhost:4200}
      CLOUD_PROVIDER: ${CLOUD_PROVIDER:-}
      SENTRY_DSN: ${SENTRY_DSN:-}
      SENTRY_HTTP_TRACING_ENABLED: ${SENTRY_HTTP_TRACING_ENABLED:-}
      SENTRY_POSTGRES_TRACKING_ENABLED: ${SENTRY_POSTGRES_TRACKING_ENABLED:-}
      SENTRY_PROFILING_ENABLED: ${SENTRY_PROFILING_ENABLED:-}
      JITSU_SERVER_URL: ${JITSU_SERVER_URL:-}
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: ${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:-}
      OTEL_EXPORTER_OTLP_HEADERS: ${OTEL_EXPORTER_OTLP_HEADERS:-}
      OTEL_ENABLED: ${OTEL_ENABLED:-}
      OTEL_PROVIDER: ${OTEL_PROVIDER:-}
      JITSU_SERVER_WRITE_KEY: ${JITSU_SERVER_WRITE_KEY:-}
      GAUZY_GITHUB_CLIENT_ID: ${GAUZY_GITHUB_CLIENT_ID:-}
      GAUZY_GITHUB_CLIENT_SECRET: ${GAUZY_GITHUB_CLIENT_SECRET:-}
      GAUZY_GITHUB_WEBHOOK_URL: ${GAUZY_GITHUB_WEBHOOK_URL:-}
      GAUZY_GITHUB_WEBHOOK_SECRET: ${GAUZY_GITHUB_WEBHOOK_SECRET:-}
      GAUZY_GITHUB_APP_PRIVATE_KEY: ${GAUZY_GITHUB_APP_PRIVATE_KEY:-}
      GAUZY_GITHUB_APP_ID: ${GAUZY_GITHUB_APP_ID:-}
      GAUZY_GITHUB_APP_NAME: ${GAUZY_GITHUB_APP_NAME:-}
      GAUZY_GITHUB_POST_INSTALL_URL: ${GAUZY_GITHUB_POST_INSTALL_URL:-}
      GAUZY_GITHUB_OAUTH_CLIENT_ID: ${GAUZY_GITHUB_OAUTH_CLIENT_ID:-}
      GAUZY_GITHUB_OAUTH_CLIENT_SECRET: ${GAUZY_GITHUB_OAUTH_CLIENT_SECRET:-}
      GAUZY_GITHUB_OAUTH_CALLBACK_URL: ${GAUZY_GITHUB_OAUTH_CALLBACK_URL:-}
      MAGIC_CODE_EXPIRATION_TIME: ${MAGIC_CODE_EXPIRATION_TIME:-}
      APP_NAME: ${APP_NAME:-}
      APP_LOGO: ${APP_LOGO:-}
      APP_SIGNATURE: ${APP_SIGNATURE:-}
      APP_LINK: ${APP_LINK:-}
      APP_EMAIL_CONFIRMATION_URL: ${APP_EMAIL_CONFIRMATION_URL:-}
      APP_MAGIC_SIGN_URL: ${APP_MAGIC_SIGN_URL:-}
      COMPANY_LINK: ${COMPANY_LINK:-}
      COMPANY_NAME: ${COMPANY_NAME:-}

    env_file:
      - .env.compose
    entrypoint: './entrypoint.compose.sh'
    command: ['node', 'main.js']
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
      zipkin:
        condition: service_started
      redis:
        condition: service_started
      minio:
        condition: service_started
      minio_create_buckets:
        condition: service_started
      elasticsearch:
        condition: service_healthy
      cube:
        condition: service_started
    links:
      - db:${DB_HOST:-db}
      - cube:${CUBE_HOST:-cube}
      - redis:${REDIS_HOST:-redis}
      - minio:${MINIO_HOST:-minio}
      - elasticsearch:${ES_HOST:-elasticsearch}
    # volumes:
    # - webapp_node_modules:/srv/gauzy/node_modules
    # - api_node_modules:/srv/gauzy/apps/api/node_modules
    ports:
      - '3000:${API_PORT:-3000}'
    networks:
      - overlay

  webapp:
    container_name: webapp
    image: ghcr.io/ever-co/ever-teams-webapp:latest
    environment:
      GAUZY_API_SERVER_URL: ${GAUZY_API_SERVER_URL:-https://api.ever.team}
      NEXT_PUBLIC_GAUZY_API_SERVER_URL: ${NEXT_PUBLIC_GAUZY_API_SERVER_URL:-https://api.ever.team}
      NODE_ENV: ${NODE_ENV:-development}
      DEMO: 'true'
    env_file:
      - .env.compose
    restart: on-failure
    links:
      - db:${DB_HOST:-db}
      - api:${API_HOST:-api}
      - cube:${CUBE_HOST:-cube}
      - redis:${REDIS_HOST:-redis}
      - minio:${MINIO_HOST:-minio}
      - elasticsearch:${ES_HOST:-elasticsearch}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      minio:
        condition: service_started
      minio_create_buckets:
        condition: service_started
      elasticsearch:
        condition: service_healthy
      api:
        condition: service_started
    # volumes:
    # - webapp_node_modules:/srv/gauzy/node_modules
    ports:
      - '3030:${UI_PORT:-3030}'
    networks:
      - overlay
