name: Desktop App Build Apps

on:
  workflow_run:
    workflows: ['Release Apps']
    branches: [apps]
    types:
      - completed

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  release-linux:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [buildjet-8vcpu-ubuntu-2204]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          repository: 'ever-co/ever-gauzy'
          ref: master

      - name: Install Node.js, NPM and Yarn
        uses: buildjet/setup-node@v3
        with:
          node-version: '20.11.1'
          cache: 'yarn'

      - name: Change permissions
        run: 'sudo chown -R $(whoami) ./*'

      - name: Install system dependencies
        run: 'sudo apt-get update && sudo apt install -y curl gnupg git libappindicator3-1 ca-certificates binutils icnsutils graphicsmagick'

      - name: Fix node-gyp and Python
        run: python3 -m pip install packaging setuptools

      - name: Install latest version of NPM
        run: 'sudo npm install -g npm@9'

      - name: Install latest node-gyp package
        run: 'sudo npm install --quiet -g node-gyp@9.3.1'

      - name: Install Yarn dependencies
        run: 'yarn install --network-timeout 1000000 --frozen-lockfile'

      - name: Bootstrap Yarn
        run: 'yarn bootstrap'

      - name: Bump version desktop timer app
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./.scripts/bump-version-electron.js')
            script.desktopTimer(true).then(console.log)
        env:
          PROJECT_REPO: 'https://github.com/ever-co/ever-teams.git'
          DESKTOP_TIMER_APP_NAME: 'ever-teams-desktop'
          COMPANY_SITE_LINK: 'https://ever.team'
          DESKTOP_TIMER_APP_DESCRIPTION: 'Ever Teams Desktop'
          DESKTOP_TIMER_APP_ID: 'com.ever.everteamsdesktop'

      - name: Build Desktop Timer App
        run: 'yarn build:desktop-timer:linux:release:gh'
        env:
          USE_HARD_LINKS: false
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          EP_GH_IGNORE_TIME: true
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_TRACES_SAMPLE_RATE: '${{ secrets.SENTRY_TRACES_SAMPLE_RATE }}'
          SENTRY_HTTP_TRACING_ENABLED: '${{ secrets.SENTRY_HTTP_TRACING_ENABLED }}'
          SENTRY_POSTGRES_TRACKING_ENABLED: '${{ secrets.SENTRY_POSTGRES_TRACKING_ENABLED }}'
          DO_KEY_ID: ${{ secrets.DO_KEY_ID }}
          DO_SECRET_KEY: ${{ secrets.DO_SECRET_KEY }}
          NX_NO_CLOUD: true
          COMPANY_SITE: 'Ever Teams'
          COMPANY_SITE_LINK: 'https://ever.team'
          COMPANY_FACEBOOK_LINK: 'https://www.facebook.com/everteamshq'
          COMPANY_TWITTER_LINK: 'https://twitter.com/ever_teams'
          COMPANY_LINKEDIN_LINK: 'https://www.linkedin.com/company/ever-co'
          PROJECT_REPO: 'https://github.com/ever-co/ever-teams.git'
          DESKTOP_TIMER_APP_NAME: 'ever-teams-desktop'
          DESKTOP_TIMER_APP_DESCRIPTION: 'Ever Teams Desktop'
          DESKTOP_TIMER_APP_ID: 'com.ever.everteamsdesktop'
          DESKTOP_TIMER_APP_REPO_NAME: 'ever-teams-desktop'
          DESKTOP_TIMER_APP_REPO_OWNER: 'ever-co'
          DESKTOP_TIMER_APP_WELCOME_TITLE: 'Welcome to Ever Teams'
          DESKTOP_TIMER_APP_WELCOME_CONTENT: 'Ever Teams is a productivity tool that helps you to stay focused on your work and manage your team work better.'
          I18N_FILES_URL: 'https://raw.githubusercontent.com/ever-co/ever-teams/develop/apps/desktop/i18n'
          PLATFORM_LOGO: 'https://app.ever.team/assets/ever-teams.png'
          GAUZY_DESKTOP_LOGO_512X512: 'https://raw.githubusercontent.com/ever-co/ever-gauzy/develop/apps/desktop-timer/src/assets/icons/icon_512x512.png'

  release-mac:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-12]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          repository: 'ever-co/ever-gauzy'
          ref: master

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'
          cache: 'yarn'

      - name: Fix node-gyp and Python
        run: python3 -m pip install packaging setuptools

      - name: Install latest version of NPM
        run: 'sudo npm install -g npm@9'

      - name: Install latest node-gyp package
        run: 'sudo npm install --quiet -g node-gyp@9.3.1'

      - name: Install Yarn dependencies
        run: 'yarn install --network-timeout 1000000 --frozen-lockfile'

      - name: Bootstrap Yarn
        run: 'yarn bootstrap'

      - name: Bump version desktop timer app
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./.scripts/bump-version-electron.js')
            script.desktopTimer(true).then(console.log)
        env:
          PROJECT_REPO: 'https://github.com/ever-co/ever-teams.git'
          DESKTOP_TIMER_APP_NAME: 'ever-teams-desktop'
          COMPANY_SITE_LINK: 'https://ever.team'
          DESKTOP_TIMER_APP_DESCRIPTION: 'Ever Teams Desktop'
          DESKTOP_TIMER_APP_ID: 'com.ever.everteamsdesktop'

      - name: Build Desktop Timer App
        run: 'yarn build:desktop-timer:mac:release'
        env:
          USE_HARD_LINKS: false
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          EP_GH_IGNORE_TIME: true
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_TRACES_SAMPLE_RATE: '${{ secrets.SENTRY_TRACES_SAMPLE_RATE }}'
          SENTRY_HTTP_TRACING_ENABLED: '${{ secrets.SENTRY_HTTP_TRACING_ENABLED }}'
          SENTRY_POSTGRES_TRACKING_ENABLED: '${{ secrets.SENTRY_POSTGRES_TRACKING_ENABLED }}'
          DO_KEY_ID: ${{ secrets.DO_KEY_ID }}
          DO_SECRET_KEY: ${{ secrets.DO_SECRET_KEY }}
          NX_NO_CLOUD: true
          COMPANY_SITE: 'Ever Teams'
          COMPANY_SITE_LINK: 'https://ever.team'
          COMPANY_FACEBOOK_LINK: 'https://www.facebook.com/everteamshq'
          COMPANY_TWITTER_LINK: 'https://twitter.com/ever_teams'
          COMPANY_LINKEDIN_LINK: 'https://www.linkedin.com/company/ever-co'
          PROJECT_REPO: 'https://github.com/ever-co/ever-teams.git'
          DESKTOP_TIMER_APP_NAME: 'ever-teams-desktop'
          DESKTOP_TIMER_APP_DESCRIPTION: 'Ever Teams Desktop'
          DESKTOP_TIMER_APP_ID: 'com.ever.everteamsdesktop'
          DESKTOP_TIMER_APP_REPO_NAME: 'ever-teams-desktop'
          DESKTOP_TIMER_APP_REPO_OWNER: 'ever-co'
          DESKTOP_TIMER_APP_WELCOME_TITLE: 'Welcome to Ever Teams'
          DESKTOP_TIMER_APP_WELCOME_CONTENT: 'Ever Teams is a productivity tool that helps you to stay focused on your work and manage your team work better.'
          I18N_FILES_URL: 'https://raw.githubusercontent.com/ever-co/ever-teams/develop/apps/desktop/i18n'
          PLATFORM_LOGO: 'https://app.ever.team/assets/ever-teams.png'
          GAUZY_DESKTOP_LOGO_512X512: 'https://raw.githubusercontent.com/ever-co/ever-gauzy/develop/apps/desktop-timer/src/assets/icons/icon_512x512.png'

  release-windows:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          repository: 'ever-co/ever-gauzy'
          ref: master

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'
          cache: 'yarn'

      - name: Fix node-gyp and Python
        run: python3 -m pip install packaging setuptools

      - name: Install latest version of NPM
        run: 'npm install -g npm@9'

      - name: Install latest node-gyp package
        run: 'npm install --quiet -g node-gyp@9.3.1'

      - name: Install Yarn dependencies
        run: 'yarn install --network-timeout 1000000 --frozen-lockfile'

      - name: Bootstrap Yarn
        run: 'yarn bootstrap'

      - name: Bump version desktop timer app
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./.scripts/bump-version-electron.js')
            script.desktopTimer(true).then(console.log)
        env:
          PROJECT_REPO: 'https://github.com/ever-co/ever-teams.git'
          DESKTOP_TIMER_APP_NAME: 'ever-teams-desktop'
          COMPANY_SITE_LINK: 'https://ever.team'
          DESKTOP_TIMER_APP_DESCRIPTION: 'Ever Teams Desktop'
          DESKTOP_TIMER_APP_ID: 'com.ever.everteamsdesktop'

      - name: Print environment variable names
        run: |
          echo "Environment Variable Names:"
          printenv | cut -d= -f1

      - name: Build Desktop Timer App
        run: 'yarn build:desktop-timer:windows:release:gh'
        env:
          USE_HARD_LINKS: false
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          EP_GH_IGNORE_TIME: true
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_TRACES_SAMPLE_RATE: '${{ secrets.SENTRY_TRACES_SAMPLE_RATE }}'
          SENTRY_HTTP_TRACING_ENABLED: '${{ secrets.SENTRY_HTTP_TRACING_ENABLED }}'
          SENTRY_POSTGRES_TRACKING_ENABLED: '${{ secrets.SENTRY_POSTGRES_TRACKING_ENABLED }}'
          DO_KEY_ID: ${{ secrets.DO_KEY_ID }}
          DO_SECRET_KEY: ${{ secrets.DO_SECRET_KEY }}
          NX_NO_CLOUD: true
          COMPANY_SITE: 'Ever Teams'
          COMPANY_SITE_LINK: 'https://ever.team'
          COMPANY_FACEBOOK_LINK: 'https://www.facebook.com/everteamshq'
          COMPANY_TWITTER_LINK: 'https://twitter.com/ever_teams'
          COMPANY_LINKEDIN_LINK: 'https://www.linkedin.com/company/ever-co'
          PROJECT_REPO: 'https://github.com/ever-co/ever-teams.git'
          DESKTOP_TIMER_APP_NAME: 'ever-teams-desktop'
          DESKTOP_TIMER_APP_DESCRIPTION: 'Ever Teams Desktop'
          DESKTOP_TIMER_APP_ID: 'com.ever.everteamsdesktop'
          DESKTOP_TIMER_APP_REPO_NAME: 'ever-teams-desktop'
          DESKTOP_TIMER_APP_REPO_OWNER: 'ever-co'
          DESKTOP_TIMER_APP_WELCOME_TITLE: 'Welcome to Ever Teams'
          DESKTOP_TIMER_APP_WELCOME_CONTENT: 'Ever Teams is a productivity tool that helps you to stay focused on your work and manage your team work better.'
          I18N_FILES_URL: 'https://raw.githubusercontent.com/ever-co/ever-teams/develop/apps/desktop/i18n'
          PLATFORM_LOGO: 'https://app.ever.team/assets/ever-teams.png'
          GAUZY_DESKTOP_LOGO_512X512: 'https://raw.githubusercontent.com/ever-co/ever-gauzy/develop/apps/desktop-timer/src/assets/icons/icon_512x512.png'
          # Override unwanted environment variables
          ACTIONS_RUNNER_ACTION_ARCHIVE_CACHE: ''
          ANT_HOME: ''
          AZURE_CONFIG_DIR: ''
          AZURE_DEVOPS_CACHE_DIR: ''
          AZURE_EXTENSION_DIR: ''
          AZ_DEVOPS_GLOBAL_CONFIG_DIR: ''
          CABAL_DIR: ''
          ChocolateyInstall: ''
          ChromeWebDriver: ''
          COBERTURA_HOME: ''
          SBT_HOME: ''
          SELENIUM_JAR_PATH: ''
          STATS_BLT: ''
          STATS_D: ''
          STATS_D_D: ''
          STATS_EXT: ''
          STATS_EXTP: ''
          STATS_RDCL: ''
          STATS_TIS: ''
          STATS_TRP: ''
          STATS_UE: ''
          STATS_V3PS: ''
          STATS_VMD: ''
          STATS_VMFE: ''
          ANDROID_HOME: ''
          ANDROID_NDK: ''
          ANDROID_NDK_HOME: ''
          ANDROID_NDK_LATEST_HOME: ''
          ANDROID_NDK_ROOT: ''
          ANDROID_SDK_ROOT: ''
          GOROOT_1_20_X64: ''
          GOROOT_1_21_X64: ''
          GOROOT_1_22_X64: ''
          GRADLE_HOME: ''
          IEWebDriver: ''
          ImageOS: ''
          ImageVersion: ''
          JAVA_HOME: ''
          JAVA_HOME_11_X64: ''
          JAVA_HOME_17_X64: ''
          JAVA_HOME_21_X64: ''
          JAVA_HOME_8_X64: ''
          M2: ''
          M2_REPO: ''
          MAVEN_OPTS: ''
          MonAgentClientLocation: ''
          PGBIN: ''
          PGDATA: ''
          PGPASSWORD: ''
          PGROOT: ''
          PGUSER: ''
          PHPROOT: ''
          PIPX_BIN_DIR: ''
          PIPX_HOME: ''
          POWERSHELL_DISTRIBUTION_CHANNEL: ''
          POWERSHELL_UPDATECHECK: ''
          PROCESSOR_ARCHITECTURE: ''
          PROCESSOR_IDENTIFIER: ''
          PROCESSOR_LEVEL: ''
          PROCESSOR_REVISION: ''
          PSModuleAnalysisCachePath: ''
          PSModulePath: ''
          DOTNET_MULTILEVEL_LOOKUP: ''
          DOTNET_NOLOGO: ''
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: ''
          DriverData: ''
          EdgeWebDriver: ''
          GCM_INTERACTIVE: ''
          GeckoWebDriver: ''
          GHCUP_INSTALL_BASE_PREFIX: ''
          GHCUP_MSYS2: ''
          RUNNER_ARCH: ''
          RUNNER_ENVIRONMENT: ''
          RUNNER_NAME: ''
          RUNNER_OS: ''
          RUNNER_PERFLOG: ''
          RUNNER_TEMP: ''
          RUNNER_TOOL_CACHE: ''
          RUNNER_TRACKING_ID: ''
          RUNNER_WORKSPACE: ''
          # PROGRAMFILES: ''
          # ProgramW6432: ''
          # ALLUSERSPROFILE: ''
          # APPDATA: ''
          # COMMONPROGRAMFILES: ''
