name: Mobile Build PROD
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/mobile.prod.yml'
      - 'apps/mobile/**'
      - 'package.json'
      - 'yarn.lock'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: prod

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install Packages
        run: |
          yarn install --frozen-lockfile

      - name: Build Mobile
        run: |
          yarn build:mobile
